# automatically generated by automakefile.pl
target = index.html


a.out: all automake up

all: $(target)

clean:
	rm $(target)

.SUFFIXES: .txt .tex .htm .html

automake:
	perl ~/Dropbox/GH/common/automakefile.pl
	perl ~/Dropbox/GH/upsftp/automakelist.pl

.txt.html:
	perl ~/Dropbox/GH/makeweb/makeweb.pl $< $@

.txt.htm:
	perl ~/Dropbox/GH/makeweb/makeweb.pl $< $@

.txt.tex:
	perl ~/Dropbox/GH/makeweb/makeweb.pl $< $@

sort:
	perl ~/Dropbox/GH/upsftp/sort.pl

up:
	perl ~/Dropbox/GH/upsftp/upsftp.pl

HOSTNAME := $(shell hostname)

# P1 (main): commit + push / others (sub): pull --rebase only
git:
	git add -A
	git diff --cached --quiet || git commit -m "auto: $$(date '+%Y-%m-%d %H:%M:%S')"
ifeq ($(HOSTNAME),P1)
	git push
else
	@echo "$(HOSTNAME): サブ機からはpushしません"
	git pull --rebase
endif
